name: photo_manager_image_provider
description: A Flutter plugin, provide image_provider for photo_manager's AssetEntity.
version: 2.1.1
homepage: https://github.com/fluttercandies/flutter_photo_manager_plugins/tree/main/packages/photo_manager_image_provider

environment:
  sdk: ">=2.13.0 <4.0.0"
  flutter: ">=3.14.0"

dependencies:
  flutter:
    sdk: flutter
  photo_manager: ">=2.6.0 <4.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
